### ISSUE TITLE
Issues building

### ISSUE THREAD

**Issue by PrimordialHelios** [james7132/py-meowhash#1]
I'm trying to build py-meowhash on Fedora 28, but I get a lot of errors related to meowhash. I've pastebinned the output of `python setup.py build` [here](https://pastebin.com/raw/M9weRrD9) because it's pretty long.

The weird part is, I can build meowhash itself just fine. Am I missing any additional steps?

**Comment by james7132** [comment]
I should probably update the README, but this repo is currently shelved until meowhash has reached a v1.0 status due to it's instability right now.

**Comment by PrimordialHelios** [comment]
Ahhh, that makes sense.

Hope that happens soon, meowhash would be perfect for my project!
